### PR TITLE
Update puppet.ts

### PR DESCRIPTION
**Pull request by su-chang**
Implement toContact() method

### CODE REVIEW

**Comment by su-chang** [comment]
1. When I add one PR link in Wechaty issue, it will generate an issue link here. Maybe I have not understand what u mean exactly.
2. I have created a new method `messageContact()` in Puppet which it doesn't have before, and then PuppetTest extends Puppet, maybe it's the reason that CI can not pass.

@huan

**Comment by huan** [comment]
> When I add one PR link in the Wechaty issue, it will generate an issue link here. 

We need to do the reverse operating as you described above:

I mean we should add the Issue link to your PR here, then this PR will generate a PR link under the Issue over there (in Wechaty repo).

> I have created a new method messageContact() in Puppet which it doesn't have before, and then PuppetTest extends Puppet, maybe it's the reason that CI can not pass.

Yes, you are right. Please fix it.

**Comment by su-chang** [comment]
Get it, thank you very much.

**Comment by huan** [comment]
@windmemory No, you should not approve this PR because it had not passed the CI test.

Please make sure the CI turns green before you approve any PR for the Wechaty project, thank you very much.

**Comment by huan** [comment]
@su-chang You are welcome.

Please follow my reviews in the previous post: they are action requirements, which need us to take action over them before we can continue the discussion.

**Comment by su-chang** [comment]
I have implemented `toContact()` method both in puppet.ts and puppet.spec.ts already, and I can run `toContact()` method successfully in local env. But the CI still thinks that I have not implemented it, I do not know where the bug is.

Maybe we should to make CI try again... How do u think about it? @huan

**Comment by su-chang** [comment]
Related issues:
https://github.com/Chatie/wechaty/issues/1627
https://github.com/Chatie/wechaty/issues/1855

**Comment by huan** [comment]
Thanks for the fix, the CI passed now!

All code looks good to me. Could you please bump the patch version up, so that we can get a new version of the NPM package after this PR was merged?

I'll merge this PR after you bumped the version up. Cheers!

**Comment by huan** [comment]
@windmemory You are 6 seconds behind me... ;-D

**Comment by windmemory** [comment]
@huan after you :P

**Comment by huan** [comment]
BTW: It would be better if we can have a more meaningful subject for this PR.

For example: `Update puppet.ts` -> `Implement toContact() method`

**Comment by huan** [comment]
@su-chang Thank you very much for enhance the puppet abstract class!

**Pull request merged**
